-- MySQL Script generated by MySQL Workbench
-- Mon Oct  6 23:43:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tienda` (
  `idTienda` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NULL DEFAULT NULL,
  `ubicacion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTienda`),
  UNIQUE INDEX `idTienda_UNIQUE` (`idTienda` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Almacen` (
  `idAlmacen` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NULL DEFAULT NULL,
  `ubicacion` VARCHAR(70) NULL DEFAULT NULL,
  `stock` INT NOT NULL,
  `Tienda_idTienda` INT NOT NULL,
  `Activo` TINYINT NOT NULL,
  PRIMARY KEY (`idAlmacen`),
  INDEX `fk_Almacen_Tienda1_idx` (`Tienda_idTienda` ASC) VISIBLE,
  CONSTRAINT `fk_Almacen_Tienda1`
    FOREIGN KEY (`Tienda_idTienda`)
    REFERENCES `mydb`.`Tienda` (`idTienda`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Prenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prenda` (
  `idPrenda` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `color` VARCHAR(30) NULL DEFAULT NULL,
  `stockPrenda` INT NOT NULL DEFAULT '0',
  `alertaMinStock` INT NOT NULL,
  `activo` TINYINT NOT NULL,
  `precioUnidad` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `precioMayor` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `precioDocena` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `material` ENUM('Algodon', 'Poliester', 'Mezcla_algodon_poliester', 'Lino', 'Viscosa_rayon', 'Lana', 'Acrilico', 'Nylon', 'Elastano_lycra', 'Denim', 'Drill', 'Gabardina', 'Polar', 'Franela', 'Cuero', 'Cuerina', 'Saten', 'Chifon') NOT NULL DEFAULT 'Algodon',
  PRIMARY KEY (`idPrenda`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Blusa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Blusa` (
  `idPrenda` INT NOT NULL,
  `tipo_blusa` ENUM('Camisera', 'CropTop', 'Peplum', 'OffShoulder', 'Transparente', 'Formal', 'Casual') NOT NULL,
  `tipo_manga` ENUM('MangaCorta', 'MangaLarga', 'SinManga', 'Globo', 'Campana', 'TresCuartos') NOT NULL,
  PRIMARY KEY (`idPrenda`),
  CONSTRAINT `Blusa_ibfk_1`
    FOREIGN KEY (`idPrenda`)
    REFERENCES `mydb`.`Prenda` (`idPrenda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`ComprobanteDePago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ComprobanteDePago` (
  `idComprobante` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL DEFAULT NULL,
  `total` DOUBLE NULL DEFAULT NULL,
  `IGV` DOUBLE NULL DEFAULT NULL,
  `metodoDePago` VARCHAR(45) NULL DEFAULT NULL,
  `correlativo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idComprobante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Boleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Boleta` (
  `idComprobante` INT NOT NULL,
  `DNI` VARCHAR(8) NULL DEFAULT NULL,
  PRIMARY KEY (`idComprobante`),
  CONSTRAINT `Boleta_ibfk_1`
    FOREIGN KEY (`idComprobante`)
    REFERENCES `mydb`.`ComprobanteDePago` (`idComprobante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT,
  `abreviatura` CHAR(1) NULL DEFAULT NULL,
  `descripcion` VARCHAR(75) NULL DEFAULT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Casaca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Casaca` (
  `idPrenda` INT NOT NULL,
  `tipo_casaca` ENUM('Bomber', 'Puffer', 'Denim', 'Deportiva', 'Cuero', 'Cardigan', 'Otro') NOT NULL,
  `con_capucha` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`idPrenda`),
  CONSTRAINT `Casaca_ibfk_1`
    FOREIGN KEY (`idPrenda`)
    REFERENCES `mydb`.`Prenda` (`idPrenda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Catalogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Catalogo` (
  `idCatalogo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NULL DEFAULT NULL,
  `Tienda_idTienda` INT NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`idCatalogo`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_Catalogo_Tienda1_idx` (`Tienda_idTienda` ASC) VISIBLE,
  CONSTRAINT `fk_Catalogo_Tienda1`
    FOREIGN KEY (`Tienda_idTienda`)
    REFERENCES `mydb`.`Tienda` (`idTienda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NULL DEFAULT NULL,
  `primerApellido` VARCHAR(75) NULL DEFAULT NULL,
  `segundoApellido` VARCHAR(45) NULL DEFAULT NULL,
  `dni` INT NULL DEFAULT NULL,
  `telefono` INT NULL DEFAULT NULL,
  `genero` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`TipoDeCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoDeCliente` (
  `tipoCliente` INT NOT NULL,
  `abreviatura` CHAR(1) NOT NULL,
  `descripcion` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`tipoCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `tipoCliente` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Persona10_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Cliente_tipoCliente10_idx` (`tipoCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Persona10`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Persona` (`idPersona`),
  CONSTRAINT `fk_Cliente_tipoCliente10`
    FOREIGN KEY (`tipoCliente`)
    REFERENCES `mydb`.`TipoDeCliente` (`tipoCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveedor` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `RUC` BIGINT NOT NULL,
  `nombre` VARCHAR(70) NULL DEFAULT NULL,
  `telefono` INT NOT NULL,
  `direccion` VARCHAR(150) NULL DEFAULT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`CondicionPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CondicionPago` (
  `idCondicion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(120) NULL DEFAULT NULL,
  `numDias` INT NOT NULL,
  `vigente` TINYINT NOT NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  PRIMARY KEY (`idCondicion`),
  INDEX `fk_Proveedor_idProveedor1_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Proveedor_idProveedor1`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`TipoCuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoCuenta` (
  `idTipoCuenta` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(75) NULL DEFAULT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`idTipoCuenta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`CuentaUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CuentaUsuario` (
  `idCuenta` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(75) NULL DEFAULT NULL,
  `contrasenha` VARCHAR(75) NULL DEFAULT NULL,
  `activo` TINYINT NOT NULL,
  `email` VARCHAR(75) NULL DEFAULT NULL,
  `TipoCuenta_idTipoCuenta` INT NOT NULL,
  PRIMARY KEY (`idCuenta`, `TipoCuenta_idTipoCuenta`),
  INDEX `fk_CuentaUsuario_TipoCuenta1_idx` (`TipoCuenta_idTipoCuenta` ASC) VISIBLE,
  CONSTRAINT `fk_CuentaUsuario_TipoCuenta1`
    FOREIGN KEY (`TipoCuenta_idTipoCuenta`)
    REFERENCES `mydb`.`TipoCuenta` (`idTipoCuenta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Vigencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vigencia` (
  `idVigencia` INT NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`idVigencia`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Descuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Descuento` (
  `idDescuento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NULL DEFAULT NULL,
  `esAutomatico` TINYINT NULL DEFAULT NULL,
  `activo` TINYINT NULL DEFAULT NULL,
  `idVigencia` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idDescuento`),
  INDEX `idVigencia` (`idVigencia` ASC) VISIBLE,
  CONSTRAINT `Descuento_ibfk_1`
    FOREIGN KEY (`idVigencia`)
    REFERENCES `mydb`.`Vigencia` (`idVigencia`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`DescuentoLiquidacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DescuentoLiquidacion` (
  `idDescuento` INT NOT NULL,
  `porcentajeLiquidacion` FLOAT NULL DEFAULT NULL,
  `condicionStockMin` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idDescuento`),
  CONSTRAINT `DescuentoLiquidacion_ibfk_1`
    FOREIGN KEY (`idDescuento`)
    REFERENCES `mydb`.`Descuento` (`idDescuento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`DescuentoMonto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DescuentoMonto` (
  `idDescuento` INT NOT NULL,
  `montoEditable` FLOAT NULL DEFAULT NULL,
  `montoMaximo` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idDescuento`),
  CONSTRAINT `DescuentoMonto_ibfk_1`
    FOREIGN KEY (`idDescuento`)
    REFERENCES `mydb`.`Descuento` (`idDescuento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`DescuentoPorcentaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DescuentoPorcentaje` (
  `idDescuento` INT NOT NULL,
  `porcentaje` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idDescuento`),
  CONSTRAINT `DescuentoPorcentaje_ibfk_1`
    FOREIGN KEY (`idDescuento`)
    REFERENCES `mydb`.`Descuento` (`idDescuento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `sueldo` DECIMAL(10,2) NULL DEFAULT NULL,
  `activo` TINYINT NOT NULL,
  `Cargo_idCargo` INT NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`, `Cargo_idCargo`),
  INDEX `fk_Empleado_Cargo1_idx` (`Cargo_idCargo` ASC) VISIBLE,
  INDEX `fk_Empleado_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `mydb`.`Cargo` (`idCargo`),
  CONSTRAINT `fk_Empleado_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `idComprobante` INT NOT NULL,
  `RUC` VARCHAR(11) NULL DEFAULT NULL,
  `razonSocial` VARCHAR(110) NULL DEFAULT NULL,
  PRIMARY KEY (`idComprobante`),
  CONSTRAINT `Factura_ibfk_1`
    FOREIGN KEY (`idComprobante`)
    REFERENCES `mydb`.`ComprobanteDePago` (`idComprobante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Falda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Falda` (
  `idPrenda` INT NOT NULL,
  `tipo_falda` ENUM('Mini', 'Midi', 'Larga', 'Tubo', 'Plisada', 'Cruzada', 'ShortFalda', 'Otro') NOT NULL,
  `largo` DECIMAL(6,2) NOT NULL,
  `con_forro` TINYINT NOT NULL DEFAULT '0',
  `con_volantes` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`idPrenda`),
  CONSTRAINT `Falda_ibfk_1`
    FOREIGN KEY (`idPrenda`)
    REFERENCES `mydb`.`Prenda` (`idPrenda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Gorro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gorro` (
  `idPrenda` INT NOT NULL,
  `tipo_gorra` ENUM('Bucket', 'Visera', 'Tejido', 'Beanie', 'Otro') NOT NULL,
  `talla_ajustable` TINYINT NOT NULL DEFAULT '0',
  `impermeable` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`idPrenda`),
  CONSTRAINT `Gorro_ibfk_1`
    FOREIGN KEY (`idPrenda`)
    REFERENCES `mydb`.`Prenda` (`idPrenda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venta` (
  `idVenta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Comprobante_idComprobante` INT NOT NULL,
  `activo` TINYINT NOT NULL DEFAULT '1',
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Empleado_idEmpleado10_idx` (`Empleado_idEmpleado` ASC) VISIBLE,
  INDEX `fk_Cliente_idCliente10_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Comprobante_idComprobante10_idx` (`Comprobante_idComprobante` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_idCliente10`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`),
  CONSTRAINT `fk_Comprobante_idComprobante10`
    FOREIGN KEY (`Comprobante_idComprobante`)
    REFERENCES `mydb`.`ComprobanteDePago` (`idComprobante`),
  CONSTRAINT `fk_Empleado_idEmpleado10`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`ItemVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItemVenta` (
  `numLinea` INT NOT NULL,
  `Prenda_idPrenda` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  `Venta_idVenta` INT NOT NULL,
  PRIMARY KEY (`numLinea`),
  INDEX `fk_Prenda_idPrenda1_idx` (`Prenda_idPrenda` ASC) VISIBLE,
  INDEX `fk_Venta_idVenta1_idx` (`Venta_idVenta` ASC) VISIBLE,
  CONSTRAINT `fk_Prenda_idPrenda1`
    FOREIGN KEY (`Prenda_idPrenda`)
    REFERENCES `mydb`.`Prenda` (`idPrenda`),
  CONSTRAINT `fk_Venta_idVenta1`
    FOREIGN KEY (`Venta_idVenta`)
    REFERENCES `mydb`.`Venta` (`idVenta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`LineaDeRopa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LineaDeRopa` (
  `idLinea` INT NOT NULL AUTO_INCREMENT,
  `nombreLinea` VARCHAR(70) NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `Catalogo_idCatalogo` INT NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`idLinea`),
  INDEX `fk_LineaDeRopa_Catalogo1_idx` (`Catalogo_idCatalogo` ASC) VISIBLE,
  CONSTRAINT `fk_LineaDeRopa_Catalogo1`
    FOREIGN KEY (`Catalogo_idCatalogo`)
    REFERENCES `mydb`.`Catalogo` (`idCatalogo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`MovimientoAlmacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MovimientoAlmacen` (
  `idMovAlmacen` INT NOT NULL AUTO_INCREMENT,
  `Almacen_idAlmacen` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `lugarDestino` VARCHAR(100) NOT NULL,
  `lugarOrigen` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`idMovAlmacen`, `Almacen_idAlmacen`),
  INDEX `fk_MovimientoAlmacen_Almacen1_idx` (`Almacen_idAlmacen` ASC) VISIBLE,
  CONSTRAINT `fk_MovimientoAlmacen_Almacen1`
    FOREIGN KEY (`Almacen_idAlmacen`)
    REFERENCES `mydb`.`Almacen` (`idAlmacen`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lote` (
  `idLote` INT NOT NULL AUTO_INCREMENT,
  `Almacen_idAlmacen` INT NOT NULL,
  `MovimientoAlmacen_idMovAlmacen` INT NOT NULL,
  `MovimientoAlmacen_Almacen_idAlmacen` INT NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`idLote`, `MovimientoAlmacen_idMovAlmacen`, `MovimientoAlmacen_Almacen_idAlmacen`),
  INDEX `fk_Lote_Almacen1_idx` (`Almacen_idAlmacen` ASC) VISIBLE,
  INDEX `fk_Lote_MovimientoAlmacen1_idx` (`MovimientoAlmacen_idMovAlmacen` ASC, `MovimientoAlmacen_Almacen_idAlmacen` ASC) VISIBLE,
  CONSTRAINT `fk_Lote_Almacen1`
    FOREIGN KEY (`Almacen_idAlmacen`)
    REFERENCES `mydb`.`Almacen` (`idAlmacen`),
  CONSTRAINT `fk_Lote_MovimientoAlmacen1`
    FOREIGN KEY (`MovimientoAlmacen_idMovAlmacen` , `MovimientoAlmacen_Almacen_idAlmacen`)
    REFERENCES `mydb`.`MovimientoAlmacen` (`idMovAlmacen` , `Almacen_idAlmacen`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`OrdenCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrdenCompra` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `fechaLlegada` DATETIME NOT NULL,
  `fechaEmision` DATETIME NOT NULL,
  `deudaPendiente` DECIMAL(10,2) NOT NULL,
  `montoTotal` DECIMAL(10,2) NOT NULL,
  `Proveedor_idProveedor` INT NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  `activo` TINYINT NOT NULL DEFAULT '1',
  PRIMARY KEY (`idCompra`),
  INDEX `fk_Empleado_idEmpleado11_idx` (`Empleado_idEmpleado` ASC) VISIBLE,
  INDEX `fk_Proveedor_idProveedor2_idx` (`Proveedor_idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_idEmpleado11`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`),
  CONSTRAINT `fk_Proveedor_idProveedor2`
    FOREIGN KEY (`Proveedor_idProveedor`)
    REFERENCES `mydb`.`Proveedor` (`idProveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`LineaLoteCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LineaLoteCompra` (
  `idPrenda` INT NOT NULL,
  `numLinea` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL DEFAULT '0',
  `talla` ENUM('XS', 'S', 'M', 'L', 'XL', 'XXL') NULL DEFAULT NULL,
  `lote_idLote` INT NOT NULL,
  `precioLote` DECIMAL(10,2) NOT NULL,
  `OrdenCompra_idCompra` INT NOT NULL,
  PRIMARY KEY (`numLinea`),
  INDEX `fk_lote_idLote1_idx` (`lote_idLote` ASC) VISIBLE,
  INDEX `fk_OrdenCompra_idCompra1_idx` (`OrdenCompra_idCompra` ASC) VISIBLE,
  CONSTRAINT `fk_lote_idLote1`
    FOREIGN KEY (`lote_idLote`)
    REFERENCES `mydb`.`Lote` (`idLote`),
  CONSTRAINT `fk_OrdenCompra_idCompra1`
    FOREIGN KEY (`OrdenCompra_idCompra`)
    REFERENCES `mydb`.`OrdenCompra` (`idCompra`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`NotaDeCredito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NotaDeCredito` (
  `idComprobante` INT NOT NULL,
  `detalleModificacion` VARCHAR(255) NULL DEFAULT NULL,
  `RUC` VARCHAR(11) NULL DEFAULT NULL,
  `razonSocial` VARCHAR(45) NULL DEFAULT NULL,
  `DNI` VARCHAR(8) NULL DEFAULT NULL,
  `motivoEspecifico` VARCHAR(255) NULL DEFAULT NULL,
  `nuevoMonto` DOUBLE NULL DEFAULT NULL,
  `valorAumentar` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idComprobante`),
  CONSTRAINT `NotaDeCredito_ibfk_1`
    FOREIGN KEY (`idComprobante`)
    REFERENCES `mydb`.`ComprobanteDePago` (`idComprobante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`NotaDeDebito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NotaDeDebito` (
  `idComprobante` INT NOT NULL,
  `detalleModificacion` VARCHAR(255) NULL DEFAULT NULL,
  `RUC` VARCHAR(11) NULL DEFAULT NULL,
  `razonSocial` VARCHAR(45) NULL DEFAULT NULL,
  `motivoEspecifico` VARCHAR(45) NULL DEFAULT NULL,
  `nuevoMonto` DOUBLE NULL DEFAULT NULL,
  `valorAumentar` DOUBLE NULL DEFAULT NULL,
  `idPrenda` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idComprobante`),
  INDEX `idPrenda` (`idPrenda` ASC) VISIBLE,
  CONSTRAINT `NotaDeDebito_ibfk_1`
    FOREIGN KEY (`idComprobante`)
    REFERENCES `mydb`.`ComprobanteDePago` (`idComprobante`),
  CONSTRAINT `NotaDeDebito_ibfk_2`
    FOREIGN KEY (`idPrenda`)
    REFERENCES `mydb`.`Prenda` (`idPrenda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Pantalon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pantalon` (
  `idPrenda` INT NOT NULL,
  `tipo_pantalon` ENUM('Jean', 'Jogger', 'Chino', 'Cargo', 'Buzo', 'Leggins', 'Palazzo', 'Otro') NOT NULL,
  `largo_pierna` DECIMAL(6,2) NOT NULL,
  `cintura` DECIMAL(6,2) NOT NULL,
  `elasticidad` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`idPrenda`),
  CONSTRAINT `Pantalon_ibfk_1`
    FOREIGN KEY (`idPrenda`)
    REFERENCES `mydb`.`Prenda` (`idPrenda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Polo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Polo` (
  `idPrenda` INT NOT NULL AUTO_INCREMENT,
  `tipo_manga` ENUM('MangaCorta', 'MangaLarga', 'SinManga', 'Globo', 'Campana', 'TresCuartos') NOT NULL,
  `estampado` VARCHAR(80) NULL DEFAULT NULL,
  `tipo_cuello` ENUM('Redondo', 'V', 'Camisero', 'Alto', 'Halter', 'OffShoulder', 'Otro') NOT NULL,
  PRIMARY KEY (`idPrenda`),
  CONSTRAINT `Polo_ibfk_1`
    FOREIGN KEY (`idPrenda`)
    REFERENCES `mydb`.`Prenda` (`idPrenda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`PrendaDescuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PrendaDescuento` (
  `idPrenda` INT NOT NULL,
  `idDescuento` INT NOT NULL,
  PRIMARY KEY (`idPrenda`, `idDescuento`),
  INDEX `idDescuento` (`idDescuento` ASC) VISIBLE,
  CONSTRAINT `PrendaDescuento_ibfk_1`
    FOREIGN KEY (`idPrenda`)
    REFERENCES `mydb`.`Prenda` (`idPrenda`),
  CONSTRAINT `PrendaDescuento_ibfk_2`
    FOREIGN KEY (`idDescuento`)
    REFERENCES `mydb`.`Descuento` (`idDescuento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`PrendaLote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PrendaLote` (
  `Prenda_idPrenda` INT NOT NULL,
  `Lote_idLote` INT NOT NULL,
  `Lote_MovimientoAlmacen_idMovAlmacen` INT NOT NULL,
  `Lote_MovimientoAlmacen_Almacen_idAlmacen` INT NOT NULL,
  `stock` INT NOT NULL,
  `activo` TINYINT NOT NULL DEFAULT '1',
  `talla` ENUM('XS', 'S', 'M', 'L', 'XL', 'XXL') NULL DEFAULT NULL,
  PRIMARY KEY (`Prenda_idPrenda`, `Lote_idLote`, `Lote_MovimientoAlmacen_idMovAlmacen`, `Lote_MovimientoAlmacen_Almacen_idAlmacen`),
  INDEX `fk_Prenda_has_Lote_Lote1_idx` (`Lote_idLote` ASC, `Lote_MovimientoAlmacen_idMovAlmacen` ASC, `Lote_MovimientoAlmacen_Almacen_idAlmacen` ASC) VISIBLE,
  INDEX `fk_Prenda_has_Lote_Prenda1_idx` (`Prenda_idPrenda` ASC) VISIBLE,
  CONSTRAINT `fk_Prenda_has_Lote_Lote1`
    FOREIGN KEY (`Lote_idLote` , `Lote_MovimientoAlmacen_idMovAlmacen` , `Lote_MovimientoAlmacen_Almacen_idAlmacen`)
    REFERENCES `mydb`.`Lote` (`idLote` , `MovimientoAlmacen_idMovAlmacen` , `MovimientoAlmacen_Almacen_idAlmacen`),
  CONSTRAINT `fk_Prenda_has_Lote_Prenda1`
    FOREIGN KEY (`Prenda_idPrenda`)
    REFERENCES `mydb`.`Prenda` (`idPrenda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Promocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Promocion` (
  `idPromocion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NULL DEFAULT NULL,
  `esAutomatico` TINYINT NULL DEFAULT NULL,
  `activo` TINYINT NULL DEFAULT NULL,
  `idVigencia` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idPromocion`),
  INDEX `idVigencia` (`idVigencia` ASC) VISIBLE,
  CONSTRAINT `Promocion_ibfk_1`
    FOREIGN KEY (`idVigencia`)
    REFERENCES `mydb`.`Vigencia` (`idVigencia`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`PrendaPromocion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PrendaPromocion` (
  `idPrenda` INT NOT NULL,
  `idPromocion` INT NOT NULL,
  PRIMARY KEY (`idPrenda`, `idPromocion`),
  INDEX `idPromocion` (`idPromocion` ASC) VISIBLE,
  CONSTRAINT `PrendaPromocion_ibfk_1`
    FOREIGN KEY (`idPrenda`)
    REFERENCES `mydb`.`Prenda` (`idPrenda`),
  CONSTRAINT `PrendaPromocion_ibfk_2`
    FOREIGN KEY (`idPromocion`)
    REFERENCES `mydb`.`Promocion` (`idPromocion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`PromocionCombo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PromocionCombo` (
  `idPromocion` INT NOT NULL AUTO_INCREMENT,
  `cantidadRequerida` INT NULL DEFAULT NULL,
  `cantidadGratis` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idPromocion`),
  CONSTRAINT `PromocionCombo_ibfk_1`
    FOREIGN KEY (`idPromocion`)
    REFERENCES `mydb`.`Promocion` (`idPromocion`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`PromocionConjunto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PromocionConjunto` (
  `idPromocion` INT NOT NULL AUTO_INCREMENT,
  `porcentajePromocion` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idPromocion`),
  CONSTRAINT `PromocionConjunto_ibfk_1`
    FOREIGN KEY (`idPromocion`)
    REFERENCES `mydb`.`Promocion` (`idPromocion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Vestido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vestido` (
  `idPrenda` INT NOT NULL,
  `tipo_vestido` ENUM('Coctel', 'Fiesta', 'Gala', 'Playa', 'Ejecutivo', 'Maxi', 'Mini', 'Casual') NOT NULL,
  `largo` INT NOT NULL,
  `tipo_manga` ENUM('MangaCorta', 'MangaLarga', 'SinManga', 'Globo', 'Campana', 'TresCuartos') NOT NULL,
  PRIMARY KEY (`idPrenda`),
  CONSTRAINT `Vestido_ibfk_1`
    FOREIGN KEY (`idPrenda`)
    REFERENCES `mydb`.`Prenda` (`idPrenda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

USE `mydb` ;

-- -----------------------------------------------------
-- procedure ELIMINAR_CARGO
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `ELIMINAR_CARGO`(
	IN _idCargo INT
)
BEGIN
	UPDATE Cargo SET activo = 0
    WHERE idCargo=_idCargo;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure INSERTAR_BOLETA
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `INSERTAR_BOLETA`(
	OUT _id_Comprobante INT,
	IN _FECHA DATETIME,
    IN _TOTAL DOUBLE,
    IN _IGV   DOUBLE,
    IN _METODOPAGO VARCHAR(45),
    IN _CORRELATIVO VARCHAR(45),
    IN _DNI VARCHAR(8)
)
BEGIN	
	INSERT INTO ComprobanteDePago(
    fecha,total,IGV,metodoDePago,correlativo)
    VALUES (_FECHA,_TOTAL,_IGV,_METODOPAGO,_CORRELATIVO);
    SET _id_Comprobante = @@last_insert_id;
	INSERT INTO Boleta(idComprobante,DNI)
    VALUES (_id_Comprobante,_DNI);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure INSERTAR_CARGO
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `INSERTAR_CARGO`(
    IN _abreviatura CHAR,
    IN _descripcion VARCHAR(75),
    IN _activo TINYINT
)
BEGIN
	INSERT INTO Cargo (abreviatura,descripcion,activo) VALUES (
		_abreviatura,_descripcion,_activo);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure INSERTAR_EMPLEADO
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `INSERTAR_EMPLEADO`(
	OUT _idEmpleado INT,
    OUT _Persona_idPersona INT,
    IN _nombre VARCHAR(75),
    IN _primerApellido VARCHAR(75),
    IN _segundoApellido VARCHAR(75),
    IN _dni INT,
    IN _telefono INT,
    IN _genero CHAR,
    IN _sueldo DECIMAL(10,2),
    IN _cargo INT
)
BEGIN
	INSERT INTO Persona (nombre,primerApellido,
    segundoApellido,dni,telefono,genero) VALUES (_nombre,
    _primerApellido, _segundoApellido,_dni,_telefono,_genero);
    SET _idEmpleado = @@last_insert_id;
    SET _Persona_idPersona = @@last_insert_id;
    INSERT INTO Empleado (idEmpleado,sueldo,activo, Cargo_idCargo,
		Persona_idPersona) VALUES (_idEmpleado,_sueldo,1,
			_cargo,_Persona_idPersona);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure INSERTAR_FACTURA
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `INSERTAR_FACTURA`(
    OUT p_idComprobante INT,
    IN p_fecha DATETIME,
    IN p_total DOUBLE,
    IN p_IGV DOUBLE,
    IN p_metodoDePago VARCHAR(45),
    IN p_correlativo VARCHAR(45),
	IN p_arregloDatosDelCorrelativo INT,
    IN p_RUC LONG,
    IN p_razonSocial VARCHAR(45)
)
BEGIN
    -- Insertar en ComprobanteDePago
    INSERT INTO ComprobanteDePago(idComprobante, fecha, total, IGV, metodoDePago, correlativo, arregloDatosDelCorrelativo)
    VALUES (p_idComprobante, p_fecha, p_total, p_IGV, p_metodoDePago, p_correlativo, p_arrCorrelativo);
    SET p_idComprobante=@@last_insert_id;
    -- Insertar en Factura
    INSERT INTO Factura(RUC, razonSocial)
    VALUES (p_RUC, p_razonSocial);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure INSERTAR_NOTA_DE_CREDITO
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `INSERTAR_NOTA_DE_CREDITO`(
	OUT _id_Comprobante INT,
	IN _FECHA DATETIME,
    IN _TOTAL DOUBLE,
    IN _IGV   DOUBLE,
    IN _METODOPAGO VARCHAR(45),
    IN _CORRELATIVO VARCHAR(45),
    IN _DETALLE_MODIFICACION VARCHAR(255),
    IN _RUC VARCHAR(11),
    IN _RAZON_SOCIAL VARCHAR(45),
    IN _DNI VARCHAR(8),
    IN _MOTIVO_ESPECIFICO VARCHAR(255),
    IN _NUEVO_MONTO DOUBLE,
    IN _VALOR_AUMENTAR DOUBLE
)
BEGIN	
	INSERT INTO ComprobanteDePago(
    fecha,total,IGV,metodoDePago,correlativo)
    VALUES (_FECHA,_TOTAL,_IGV,_METODOPAGO,_CORRELATIVO);
    SET _id_Comprobante = @@last_insert_id;
	INSERT INTO NotaDeCredito(idComprobante,detalleModificacion,
		RUC,razonSocial,DNI,motivoEspecifico,nuevoMonto,valorAumentar)
    VALUES (_id_Comprobante,_DETALLE_MODIFICACION,_RUC,
		_RAZON_SOCIAL,_DNI,_MOTIVO_ESPECIFICO,_NUEVO_MONTO,
        _VALOR_AUMENTAR);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure INSERTAR_NOTA_DE_DEBITO
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `INSERTAR_NOTA_DE_DEBITO`(
	OUT _id_Comprobante INT,
	IN _FECHA DATETIME,
    IN _TOTAL DOUBLE,
    IN _IGV   DOUBLE,
    IN _METODOPAGO VARCHAR(45),
    IN _CORRELATIVO VARCHAR(45),
    IN _DETALLE_MODIFICACION VARCHAR(255),
    IN _RUC VARCHAR(11),
    IN _RAZON_SOCIAL VARCHAR(45),
    IN _MOTIVO_ESPECIFICO VARCHAR(45),
    IN _NUEVO_MONTO DOUBLE,
    IN _VALOR_AUMENTAR DOUBLE,
    IN _ID_PRENDA INT
)
BEGIN	
	INSERT INTO ComprobanteDePago(
    fecha,total,IGV,metodoDePago,correlativo)
    VALUES (_FECHA,_TOTAL,_IGV,_METODOPAGO,_CORRELATIVO);
    SET _id_Comprobante = @@last_insert_id;
	INSERT INTO NotaDeDebito(idComprobante,detalleModificacion,RUC,razonSocial,
		motivoEspecifico,nuevoMonto,valorAumentar,idPrenda)
    VALUES (_id_Comprobante,_DETALLE_MODIFICACION,
    _RUC,_RAZON_SOCIAL,_MOTIVO_ESPECIFICO,_NUEVO_MONTO,
    _VALOR_AUMENTAR,_ID_PRENDA);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure MODIFICAR_BOLETA
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `MODIFICAR_BOLETA`(
	IN _id_Comprobante INT,
	IN _FECHA DATETIME,
    IN _TOTAL DOUBLE,
    IN _IGV   DOUBLE,
    IN _METODOPAGO VARCHAR(45),
    IN _CORRELATIVO VARCHAR(45),
    IN _DNI VARCHAR(8)
)
BEGIN	
	UPDATE ComprobanteDePago SET 
    fecha=_FECHA,total=_TOTAL,IGV=_IGV,metodoDePago=_METODOPAGO
    ,correlativo = _CORRELATIVO WHERE idComprobante=_id_Comprobante;
	UPDATE Boleta SET DNI = _DNI WHERE idComprobante = _id_Comprobante;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure MODIFICAR_CARGO
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `MODIFICAR_CARGO`(
	IN _idCargo INT,
	IN _abreviatura CHAR,
    IN _descripcion VARCHAR(75),
    IN _activo TINYINT
)
BEGIN
	UPDATE Cargo
    SET abreviatura=_abreviatura,
    descripcion=_descripcion,
    activo=_activo
    WHERE idCargo=_idCargo;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure MOSTRAR_CARGOS
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `MOSTRAR_CARGOS`()
BEGIN
	SELECT *
    FROM Cargo;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure MOSTRAR_PROMOCIONCOMBOS
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `MOSTRAR_PROMOCIONCOMBOS`()
Begin

select * from PromocionCombo;

End$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure MOSTRAR_PROMOCIONCONJUNTO
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `MOSTRAR_PROMOCIONCONJUNTO`()
Begin

select * from PromocionConjunto;

End$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure OBTENER_BOLETA_X_ID
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `OBTENER_BOLETA_X_ID`(
	IN _id_Comprobante INT
)
BEGIN
	SELECT b.idComprobante, p.correlativo, p.fecha, p.IGV, p.metodoDePago, p.total, b.DNI FROM ComprobanteDePago p INNER JOIN Boleta b ON p.idComprobante = b.idComprobante WHERE b.idComprobante = _id_Comprobante;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure OBTENER_CARGO_X_ID
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `OBTENER_CARGO_X_ID`(
	IN _idCargo INT
)
BEGIN
	SELECT *
    FROM Cargo
    WHERE idCargo=_idCargo;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure OBTENER_CASACA_X_IDCasaca
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `OBTENER_CASACA_X_IDCasaca`(
    IN _id_prenda INT
)
BEGIN
    SELECT  p.idPrenda, p.nombre, p.stockPrenda, p.precioUnidad, p.precioMayor, p.precioDocena,
            p.alertaMinStock, p.color, p.material,
            c.tipo_casaca, c.con_capucha
      FROM  Prenda p
      JOIN  Casaca c ON c.idPrenda = p.idPrenda
     WHERE  p.idPrenda = _id_prenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure OBTENER_PROMOCIONCOMBO_X_ID
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `OBTENER_PROMOCIONCOMBO_X_ID`(in id int)
Begin 
	select * from PromocionCombo where idPromocion=id;
End$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure OBTENER_PROMOCIONCONJUNTO_X_ID
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `OBTENER_PROMOCIONCONJUNTO_X_ID`(in id int)
Begin 
	select * from PromocionConjunto where idPromocion=id;
End$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure eliminar_almacen
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `eliminar_almacen`(
	_idAlmacen int
)
BEGIN 
	UPDATE Almacen SET activo=0 
    WHERE idAlmacen=_idAlmacen;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure eliminar_blusa
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `eliminar_blusa`(
    IN _idPrenda INT
)
BEGIN
  UPDATE Prenda
     SET activo = 0
   WHERE idPrenda = _idPrenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure eliminar_descuentoLiquidacion
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `eliminar_descuentoLiquidacion`(in id int)
BEGIN
		update Promocion 
        set activo=0
        where idPromocion=id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure eliminar_descuentoMonto
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `eliminar_descuentoMonto`(in id int)
BEGIN
		update Descuento 
        set activo=0
        where idDescuento=id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure eliminar_descuentoPorcentaje
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `eliminar_descuentoPorcentaje`(in id int)
BEGIN
		update Descuento 
        set activo=0
        where idDescuento=id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure eliminar_falda
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `eliminar_falda`(
		IN _idPrenda INT )
BEGIN
  UPDATE Prenda SET activo=0
  WHERE idPrenda=_idPrenda;
  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure eliminar_gorro
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `eliminar_gorro`(
    IN _idPrenda INT
)
BEGIN
  UPDATE Prenda
     SET activo = 0
   WHERE idPrenda = _idPrenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure eliminar_lote
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `eliminar_lote`(
	_idLote int
)
BEGIN
	UPDATE Lote SET activo=0
	WHERE idLote=_idLote;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure eliminar_mov_almacen
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `eliminar_mov_almacen`(
	_idMovAlmacen INT
)
BEGIN
	UPDATE MovimientoAlmacen
    SET activo=0
    WHERE idMovAlmacen=_idMovAlmacen;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure eliminar_pantalon
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `eliminar_pantalon`(
    IN _idPrenda INT
)
BEGIN
  UPDATE Prenda
     SET activo = 0
   WHERE idPrenda = _idPrenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure eliminar_promocioncombo
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `eliminar_promocioncombo`(in id int)
BEGIN
		update Promocion 
        set activo=0
        where idPromocion=id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure eliminar_promocionconjunto
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `eliminar_promocionconjunto`(in id int)
BEGIN
		update Promocion 
        set activo=0
        where idPromocion=id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure eliminar_proveedor
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `eliminar_proveedor`(
		IN _idProveedor INT )
BEGIN
  UPDATE Proveedor SET activo=0
  WHERE idProveedor=_idProveedor;
  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure eliminar_vestido
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `eliminar_vestido`(
    IN _idPrenda INT
)
BEGIN
  UPDATE Prenda
     SET activo = 0
   WHERE idPrenda = _idPrenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertar_almacen
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `insertar_almacen`(
	OUT _id_almacen INT,
    IN _nombre varchar(70),
    IN _ubicacion varchar(70),
    IN _stock int,
    IN _Tienda_idTienda int
)
BEGIN
	INSERT INTO Almacen(nombre, ubicacion, stock, Activo, Tienda_idTienda)
    VALUES (_nombre, _ubicacion, _stock, 1,_Tienda_idTienda);
    SET _id_almacen = @@last_insert_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertar_blusa
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `insertar_blusa`(
    OUT _id_prenda INT,
    IN  _nombre VARCHAR(100),
    IN  _precioUnidad DECIMAL(10,2),
    IN  _precioMayor  DECIMAL(10,2),
    IN  _precioDocena DECIMAL(10,2),
    IN  _alertaMinStock INT,
    IN  _color VARCHAR(30),
    IN  _material ENUM('Algodon','Poliester','Mezcla_algodon_poliester','Lino','Viscosa_rayon',
                       'Lana','Acrilico','Nylon','Elastano_lycra','Denim','Drill','Gabardina',
                       'Polar','Franela','Cuero','Cuerina','Saten','Chifon'),
    IN  _tipo_blusa ENUM('Camisera','CropTop','Peplum','OffShoulder','Transparente','Formal','Casual'),
    IN  _tipo_manga ENUM('MangaCorta','MangaLarga','SinManga','Globo','Campana','TresCuartos')
)
BEGIN
    INSERT INTO Prenda(nombre, activo, precioUnidad, precioMayor, precioDocena,
                       alertaMinStock, color, material)
    VALUES(_nombre, 1, _precioUnidad, _precioMayor, _precioDocena,
           _alertaMinStock, _color, _material);

    SET _id_prenda = LAST_INSERT_ID();

    INSERT INTO Blusa(idPrenda, tipo_blusa, tipo_manga)
    VALUES(_id_prenda, _tipo_blusa, _tipo_manga);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertar_casaca
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `insertar_casaca`(
	OUT  _id_prenda INT,
    IN  _nombre VARCHAR(100),
    IN  _precioUnidad DECIMAL(10,2),
    IN  _precioMayor  DECIMAL(10,2),
    IN  _precioDocena DECIMAL(10,2),
    IN  _alertaMinStock INT,
    IN  _color VARCHAR(30),
    IN  _material ENUM('Algodon','Poliester','Mezcla_algodon_poliester','Lino','Viscosa_rayon',
                       'Lana','Acrilico','Nylon','Elastano_lycra','Denim','Drill','Gabardina',
                       'Polar','Franela','Cuero','Cuerina','Saten','Chifon'),
    IN  _tipo_casaca  ENUM('Bomber','Puffer','Denim','Deportiva','Cuero','Cardigan','Otro'),
    IN  _con_capucha TINYINT    
)
BEGIN
	INSERT INTO Prenda(nombre, activo, precioUnidad, precioMayor, precioDocena,
                       alertaMinStock, color, material)
    VALUES(_nombre, 1, _precioUnidad, _precioMayor, _precioDocena,
           _alertaMinStock, _color, _material);

    SET _id_prenda = @@last_insert_id;

    INSERT INTO Casaca(idPrenda, tipo_casaca, con_capucha)
    VALUES(_id_prenda, _tipo_casaca, _con_capucha);

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertar_cliente
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `insertar_cliente`(  OUT _idCliente INT,     
IN _nombre VARCHAR(75),     IN _primerApellido VARCHAR(75),   
  IN _segundoApellido VARCHAR(75),     IN _dni INT,
  IN _telefono INT, IN _genero CHAR , IN _abreviatura CHAR(1),
  IN _descripcion VARCHAR(120), IN _tipoCliente INT
  )
BEGIN  
  
  INSERT INTO Persona(nombre, primerApellido,segundoApellido,
  dni,telefono, genero) 
  VALUES (_nombre, _primerApellido, _segundoApellido, _dni ,
   _telefono  , _genero);  

  SET _idCliente = @@last_insert_id;
  
  
  INSERT INTO TipoDeCliente(tipoCliente,abreviatura, descripcion) 
  VALUES (_tipoCliente,_abreviatura, _descripcion);  
  
  INSERT INTO Cliente(idCliente,tipoCliente) VALUES (_idCliente,_tipoCliente);
  
  
  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertar_descuentomonto
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `insertar_descuentomonto`(out id INT,in nom VARCHAR(75),in montoE float,in montoM float,in idV int)
begin 
	insert into Descuento (nombre,activo,esAutomatico,idVigencia) values (nom,1,1,idV);
	set id=@@last_insert_id;
    insert into DescuentoMonto(idDescuento,montoEditable,montoMaximo) values (id,montoE,montoM);
	
	
end$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertar_descuentoporcentaje
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `insertar_descuentoporcentaje`(out id INT,in nom VARCHAR(75),in porcentaje float,in idV int)
begin 
	insert into Descuento (nombre,activo,esAutomatico,idVigencia) values (nom,1,1,idV);
	set id=@@last_insert_id;
    insert into DescuentoPorcentaje(idDescuento,porcentaje) values (id,porcentaje);
	
	
end$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertar_falda
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `insertar_falda`(
    OUT _id_prenda INT,
    IN  _nombre VARCHAR(100),
    IN  _precioUnidad DECIMAL(10,2),
    IN  _precioMayor  DECIMAL(10,2),
    IN  _precioDocena DECIMAL(10,2),
    IN  _alertaMinStock INT,
    IN  _color VARCHAR(30),
    IN  _material ENUM('Algodon','Poliester','Mezcla_algodon_poliester','Lino','Viscosa_rayon',
                       'Lana','Acrilico','Nylon','Elastano_lycra','Denim','Drill','Gabardina',
                       'Polar','Franela','Cuero','Cuerina','Saten','Chifon'),
    IN  _tipo_falda   ENUM('Mini','Midi','Larga','Tubo','Plisada','Cruzada','ShortFalda','Otro'),
    IN  _largo        DECIMAL(6,2),
    IN  _con_forro    TINYINT,
    IN  _con_volantes TINYINT
)
BEGIN
    INSERT INTO Prenda(nombre, activo, precioUnidad, precioMayor, precioDocena,
                       alertaMinStock, color, material)
    VALUES(_nombre, 1, _precioUnidad, _precioMayor, _precioDocena,
           _alertaMinStock, _color, _material);

    SET _id_prenda = @@last_insert_id;

    INSERT INTO Falda(idPrenda, tipo_falda, largo, con_forro, con_volantes)
    VALUES(_id_prenda, _tipo_falda, _largo, _con_forro, _con_volantes);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertar_gorro
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `insertar_gorro`(
    OUT _id_prenda INT,
    IN  _nombre VARCHAR(100),
    IN  _precioUnidad DECIMAL(10,2),
    IN  _precioMayor  DECIMAL(10,2),
    IN  _precioDocena DECIMAL(10,2),
    IN  _alertaMinStock INT,
    IN  _color VARCHAR(30),
    IN  _material ENUM('Algodon','Poliester','Mezcla_algodon_poliester','Lino','Viscosa_rayon',
                       'Lana','Acrilico','Nylon','Elastano_lycra','Denim','Drill','Gabardina',
                       'Polar','Franela','Cuero','Cuerina','Saten','Chifon'),
    IN  _tipo_gorra ENUM('Bucket','Visera','Tejido','Beanie','Otro'),
    IN  _talla_ajustable TINYINT,
    IN  _impermeable     TINYINT
)
BEGIN
    INSERT INTO Prenda(nombre, activo, precioUnidad, precioMayor, precioDocena,
                       alertaMinStock, color, material)
    VALUES(_nombre, 1, _precioUnidad, _precioMayor, _precioDocena,
           _alertaMinStock, _color, _material);

    SET _id_prenda = LAST_INSERT_ID();

    INSERT INTO Gorro(idPrenda, tipo_gorra, talla_ajustable, impermeable)
    VALUES(_id_prenda, _tipo_gorra, _talla_ajustable, _impermeable);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertar_lote
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `insertar_lote`(
	OUT _idLote int,
    _Almacen_idAlmacen int,
    _MovimientoAlmacen_idMov_Almacen int,
    _MovimientoAlmacen_Almacen_idAlmacen int
)
BEGIN
	INSERT INTO Lote(idLote, Almacen_idAlmacen, MovimientoAlmacen_idMovAlmacen,
    MovimientoAlmacen_Almacen_idAlmacen, activo)
    VALUES (_idLote, _Almacen_idAlmacen, _MovimientoAlmacen_idMov_Almacen,
	_MovimientoAlmacen_Almacen_idAlmacen,  1);
	
	SET _idLote=@@last_insert_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertar_mov_almacen
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `insertar_mov_almacen`(
	OUT _idMovAlmacen int,
    _Almacen_idAlmacen int,
    _fecha DATE,
    _lugarDestino VARCHAR(100),
    _lugarOrigen VARCHAR(100),
    _tipo ENUM('Entrada', 'Salida', 'Mov_Interno')
)
BEGIN
	INSERT INTO MovimientoAlmacen(idMovAlmacen, Almacen_idAlmacen, fecha,
    lugarDestino, lugarOrigen, tipo, activo)
    VALUES (_idMovAlmacen, _Almacen_idAlmacen, _fecha,
	_lugarDestino, _lugarOrigen, _tipo, 1);
	
	SET _idMovAlmacen=@@last_insert_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertar_pantalon
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `insertar_pantalon`(
    OUT _id_prenda INT,
    IN  _nombre VARCHAR(100),
    IN  _precioUnidad DECIMAL(10,2),
    IN  _precioMayor  DECIMAL(10,2),
    IN  _precioDocena DECIMAL(10,2),
    IN  _alertaMinStock INT,
    IN  _color VARCHAR(30),
    IN  _material ENUM('Algodon','Poliester','Mezcla_algodon_poliester','Lino','Viscosa_rayon',
                       'Lana','Acrilico','Nylon','Elastano_lycra','Denim','Drill','Gabardina',
                       'Polar','Franela','Cuero','Cuerina','Saten','Chifon'),
    IN  _tipo_pantalon ENUM('Jean','Jogger','Chino','Cargo','Buzo','Leggins','Palazzo','Otro'),
    IN  _largo_pierna DECIMAL(6,2),
    IN  _cintura      DECIMAL(6,2),
    IN  _elasticidad  TINYINT
)
BEGIN
    INSERT INTO Prenda(nombre, activo, precioUnidad, precioMayor, precioDocena,
                       alertaMinStock, color, material)
    VALUES(_nombre, 1, _precioUnidad, _precioMayor, _precioDocena,
           _alertaMinStock, _color, _material);

    SET _id_prenda = LAST_INSERT_ID();

    INSERT INTO Pantalon(idPrenda, tipo_pantalon, largo_pierna, cintura, elasticidad)
    VALUES(_id_prenda, _tipo_pantalon, _largo_pierna, _cintura, _elasticidad);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertar_polo
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `insertar_polo`(
    OUT _id_prenda INT,
    IN  _nombre VARCHAR(100),
    IN  _precioUnidad DECIMAL(10,2),
    IN  _precioMayor  DECIMAL(10,2),
    IN  _precioDocena DECIMAL(10,2),
    IN  _alertaMinStock INT,
    IN  _color VARCHAR(30),
    IN  _material ENUM('Algodon','Poliester','Mezcla_algodon_poliester','Lino','Viscosa_rayon',
                       'Lana','Acrilico','Nylon','Elastano_lycra','Denim','Drill','Gabardina',
                       'Polar','Franela','Cuero','Cuerina','Saten','Chifon'),
    IN  _tipo_manga  ENUM('MangaCorta','MangaLarga','SinManga','Globo','Campana','TresCuartos'),
    IN  _estampado   VARCHAR(80),
    IN  _tipo_cuello ENUM('Redondo','V','Camisero','Alto','Halter','OffShoulder','Otro')
)
BEGIN

    INSERT INTO Prenda(nombre, activo, precioUnidad, precioMayor, precioDocena,
                       alertaMinStock, color, material)
    VALUES(_nombre, 1, _precioUnidad, _precioMayor, _precioDocena,
           _alertaMinStock, _color, _material);

    SET _id_prenda = @@last_insert_id;

    INSERT INTO Polo(idPrenda, tipo_manga, estampado, tipo_cuello)
    VALUES(_id_prenda, _tipo_manga, _estampado, _tipo_cuello);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertar_promocioncombo
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `insertar_promocioncombo`(out id INT,in nom VARCHAR(75),in cantReque INT, in cantGrat int ,in idV int)
begin 
	insert into Promocion (nombre,activo,esAutomatico,idVigencia) values (nom,1,1,idV);
	set id=@@last_insert_id;
    insert into PromocionCombo(idPromocion,cantidadRequerida,cantidadGratis) values (id,cantReque,cantGrat);
	
	
end$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertar_promocionconjunto
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `insertar_promocionconjunto`(out id INT,in nom VARCHAR(75),in porcentaje float,in idV int)
begin 
	insert into Promocion (nombre,activo,esAutomatico,idVigencia) values (nom,1,1,idV);
	set id=@@last_insert_id;
    insert into PromocionConjunto(idPromocion,porcentajePromocion) values (id,porcentaje);
	
	
end$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertar_proveedor
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `insertar_proveedor`(  OUT _idProveedor INT,     
IN _RUC BIGINT,     IN _nombre VARCHAR(70),   
  IN _telefono INT,     IN _direccion VARCHAR(150))
BEGIN  
  INSERT INTO Proveedor(RUC, nombre,telefono,     direccion,activo) 
  VALUES (_RUC, _nombre, _telefono, _direccion ,1);  
  SET _idProveedor = @@last_insert_id; 
  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure insertar_vestido
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `insertar_vestido`(
    OUT _id_prenda INT,
    IN  _nombre VARCHAR(100),
    IN  _precioUnidad DECIMAL(10,2),
    IN  _precioMayor  DECIMAL(10,2),
    IN  _precioDocena DECIMAL(10,2),
    IN  _alertaMinStock INT,
    IN  _color VARCHAR(30),
    IN  _material ENUM('Algodon','Poliester','Mezcla_algodon_poliester','Lino','Viscosa_rayon',
                       'Lana','Acrilico','Nylon','Elastano_lycra','Denim','Drill','Gabardina',
                       'Polar','Franela','Cuero','Cuerina','Saten','Chifon'),
    IN  _tipo_vestido ENUM('Coctel','Fiesta','Gala','Playa','Ejecutivo','Maxi','Mini','Casual'),
    IN  _tipo_manga   ENUM('MangaCorta','MangaLarga','SinManga','Globo','Campana','TresCuartos'),
    IN  _largo        INT
)
BEGIN
    INSERT INTO Prenda(nombre, activo, precioUnidad, precioMayor, precioDocena,
                       alertaMinStock, color, material)
    VALUES(_nombre, 1, _precioUnidad, _precioMayor, _precioDocena,
           _alertaMinStock, _color, _material);

    SET _id_prenda = LAST_INSERT_ID();

    INSERT INTO Vestido(idPrenda, tipo_vestido, largo, tipo_manga)
    VALUES(_id_prenda, _tipo_vestido, _largo, _tipo_manga);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure listar_clientes
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `listar_clientes`()
BEGIN
  
  
  SELECT c.idCliente,p.nombre,
    p.primerApellido,p.segundoApellido,
    p.dni,p.telefono,p.genero,
    t.tipoCliente,t.abreviatura,t.descripcion
    FROM Cliente c INNER JOIN 
	Persona p ON c.idCliente=p.idPersona
	INNER JOIN TipoDeCliente t ON c.tipoCliente = t.tipoCliente;
  
  
  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure listar_proveedores
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `listar_proveedores`()
BEGIN
  Select idProveedor,RUC,nombre,telefono,direccion,activo
  From Proveedor;
  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificar_almacen
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `modificar_almacen`(
	_id int,
	_nombre varchar(70),
    _ubicacion varchar(70),
    _stock int,
    _activo tinyint,
    _idTienda int
)
BEGIN
	UPDATE Almacen 
    SET nombre=_nombre, ubicacion=_ubicacion, stock=_stock, activo=_activo, 
		Tienda_idTienda=_idTienda
    WHERE _id=idAlmacen;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificar_blusa
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `modificar_blusa`(
    IN  _id_prenda INT,
    IN  _nombre VARCHAR(100),
    IN  _precioUnidad DECIMAL(10,2),
    IN  _precioMayor  DECIMAL(10,2),
    IN  _precioDocena DECIMAL(10,2),
    IN  _alertaMinStock INT,
    IN  _color VARCHAR(30),
    IN  _material ENUM('Algodon','Poliester','Mezcla_algodon_poliester','Lino','Viscosa_rayon',
                       'Lana','Acrilico','Nylon','Elastano_lycra','Denim','Drill','Gabardina',
                       'Polar','Franela','Cuero','Cuerina','Saten','Chifon'),
    IN  _tipo_blusa ENUM('Camisera','CropTop','Peplum','OffShoulder','Transparente','Formal','Casual'),
    IN  _tipo_manga ENUM('MangaCorta','MangaLarga','SinManga','Globo','Campana','TresCuartos'),
    IN  _activo     TINYINT
)
BEGIN
    UPDATE Prenda
       SET nombre        = _nombre,
           precioUnidad  = _precioUnidad,
           precioMayor   = _precioMayor,
           precioDocena  = _precioDocena,
           alertaMinStock= _alertaMinStock,
           color         = _color,
           material      = _material,
           activo        = _activo
     WHERE idPrenda = _id_prenda;

    UPDATE Blusa
       SET tipo_blusa = _tipo_blusa,
           tipo_manga = _tipo_manga
     WHERE idPrenda = _id_prenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificar_casaca
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `modificar_casaca`(
	IN  _id_prenda INT,
    IN  _nombre VARCHAR(100),
    IN  _precioUnidad DECIMAL(10,2),
    IN  _precioMayor  DECIMAL(10,2),
    IN  _precioDocena DECIMAL(10,2),
    IN  _alertaMinStock INT,
    IN  _color VARCHAR(30),
    IN  _material ENUM('Algodon','Poliester','Mezcla_algodon_poliester','Lino','Viscosa_rayon',
                       'Lana','Acrilico','Nylon','Elastano_lycra','Denim','Drill','Gabardina',
                       'Polar','Franela','Cuero','Cuerina','Saten','Chifon'),
    IN  _tipo_casaca  ENUM('Bomber','Puffer','Denim','Deportiva','Cuero','Cardigan','Otro'),
    IN  _con_capucha TINYINT,
    IN  _activo TINYINT
)
BEGIN
	UPDATE Prenda
       SET nombre = _nombre,
           precioUnidad = _precioUnidad,
           precioMayor  = _precioMayor,
           precioDocena = _precioDocena,
           alertaMinStock = _alertaMinStock,
           color = _color,
           material = _material,
           activo = _activo
     WHERE idPrenda = _id_prenda;

    UPDATE Casaca
       SET tipo_casaca  = _tipo_casaca,
           con_capucha = _con_capucha
     WHERE idPrenda = _id_prenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificar_cliente
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `modificar_cliente`(  IN _idCliente INT,     
IN _nombre VARCHAR(75),     IN _primerApellido VARCHAR(75),   
  IN _segundoApellido VARCHAR(75),     IN _dni INT,
  IN _telefono INT, IN _genero CHAR , IN _abreviatura CHAR(1),
  IN _descripcion VARCHAR(120), IN _tipoCliente INT
  )
BEGIN  
  
  UPDATE Persona SET nombre=_nombre,
  primerApellido=_primerApellido,
  segundoApellido=_segundoApellido,
  dni=_dni,
  telefono=_telefono,
  genero=_genero
  WHERE idPersona=_idCliente;
  
  UPDATE TipoDeCliente SET 
  abreviatura=_abreviatura,
  descripcion=_descripcion
  WHERE tipoCliente=_tipoCliente;
  
  
  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificar_descuentomonto
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `modificar_descuentomonto`(in id int, in nomb VARCHAR(75),in montoE float,in montoD float)
BEGIN
		update Descuento 
        set nombre=nomb
        where idDescuento=id;
        
		update DescuentoMonto 
        set montoEditable=montoE, montoMaximo=montoD
        where idDescuento=id;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificar_descuentoporcentaje
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `modificar_descuentoporcentaje`(in id int, in nomb VARCHAR(75),in porcen float )
BEGIN
		update Descuento 
        set nombre=nomb
        where idDescuento=id;
        
		update DescuentoPorcentaje 
        set porcentaje=porcen
        where idPromocion=id;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificar_falda
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `modificar_falda`(
    IN  _id_prenda INT,
    IN  _nombre VARCHAR(100),
    IN  _precioUnidad DECIMAL(10,2),
    IN  _precioMayor  DECIMAL(10,2),
    IN  _precioDocena DECIMAL(10,2),
    IN  _alertaMinStock INT,
    IN  _color VARCHAR(30),
    IN  _material ENUM('Algodon','Poliester','Mezcla_algodon_poliester','Lino','Viscosa_rayon',
                       'Lana','Acrilico','Nylon','Elastano_lycra','Denim','Drill','Gabardina',
                       'Polar','Franela','Cuero','Cuerina','Saten','Chifon'),
    IN  _tipo_falda   ENUM('Mini','Midi','Larga','Tubo','Plisada','Cruzada','ShortFalda','Otro'),
    IN  _largo        DECIMAL(6,2),
    IN  _con_forro    TINYINT,
    IN  _con_volantes TINYINT,
    IN  _activo       TINYINT
)
BEGIN
    UPDATE Prenda
       SET nombre = _nombre,
           precioUnidad = _precioUnidad,
           precioMayor  = _precioMayor,
           precioDocena = _precioDocena,
           alertaMinStock = _alertaMinStock,
           color = _color,
           material = _material,
           activo = _activo
     WHERE idPrenda = _id_prenda;

    UPDATE Falda
       SET tipo_falda   = _tipo_falda,
           largo        = _largo,
           con_forro    = _con_forro,
           con_volantes = _con_volantes
     WHERE idPrenda = _id_prenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificar_gorro
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `modificar_gorro`(
    IN  _id_prenda INT,
    IN  _nombre VARCHAR(100),
    IN  _precioUnidad DECIMAL(10,2),
    IN  _precioMayor  DECIMAL(10,2),
    IN  _precioDocena DECIMAL(10,2),
    IN  _alertaMinStock INT,
    IN  _color VARCHAR(30),
    IN  _material ENUM('Algodon','Poliester','Mezcla_algodon_poliester','Lino','Viscosa_rayon',
                       'Lana','Acrilico','Nylon','Elastano_lycra','Denim','Drill','Gabardina',
                       'Polar','Franela','Cuero','Cuerina','Saten','Chifon'),
    IN  _tipo_gorra ENUM('Bucket','Visera','Tejido','Beanie','Otro'),
    IN  _talla_ajustable TINYINT,
    IN  _impermeable     TINYINT,
    IN  _activo          TINYINT
)
BEGIN
    UPDATE Prenda
       SET nombre        = _nombre,
           precioUnidad  = _precioUnidad,
           precioMayor   = _precioMayor,
           precioDocena  = _precioDocena,
           alertaMinStock= _alertaMinStock,
           color         = _color,
           material      = _material,
           activo        = _activo
     WHERE idPrenda = _id_prenda;

    UPDATE Gorro
       SET tipo_gorra      = _tipo_gorra,
           talla_ajustable = _talla_ajustable,
           impermeable     = _impermeable
     WHERE idPrenda = _id_prenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificar_lote
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `modificar_lote`(
	_idLote int,
    _Almacen_idAlmacen int,
    _MovimientoAlmacen_idMov_Almacen int,
    _MovimientoAlmacen_Almacen_idAlmacen int,
    _activo TINYINT
)
BEGIN
	UPDATE Lote SET Almacen_idAlmacen=_Almacen_idAlmacen, 
		MovimientoAlmacen_idMovAlmacen=_MovimientoAlmacen_idMov_Almacen,
        MovimientoAlmacen_Almacen_idAlmacen=_MovimientoAlmacen_Almacen_idAlmacen, activo=_activo
	WHERE idLote=_idLote;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificar_mov_almacen
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `modificar_mov_almacen`(
	_idMovAlmacen int,
    _Almacen_idAlmacen int,
    _fecha DATE,
    _lugarDestino VARCHAR(100),
    _lugarOrigen VARCHAR(100),
    _tipo_lote ENUM('Entrada', 'Salida', 'Mov_Interno'),
    _activo TINYINT
)
BEGIN
	UPDATE MovimientoAlmacen
    SET Almacen_idAlmacen=_Almacen_idAlmacen, fecha=_fecha,
    lugarDestino=_lugarDestino, lugarOrigen=_lugarOrigen, tipo=_tipo_lote, activo=_activo
    WHERE idMovAlmacen=_idMovAlmacen;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificar_pantalon
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `modificar_pantalon`(
    IN  _id_prenda INT,
    IN  _nombre VARCHAR(100),
    IN  _precioUnidad DECIMAL(10,2),
    IN  _precioMayor  DECIMAL(10,2),
    IN  _precioDocena DECIMAL(10,2),
    IN  _alertaMinStock INT,
    IN  _color VARCHAR(30),
    IN  _material ENUM('Algodon','Poliester','Mezcla_algodon_poliester','Lino','Viscosa_rayon',
                       'Lana','Acrilico','Nylon','Elastano_lycra','Denim','Drill','Gabardina',
                       'Polar','Franela','Cuero','Cuerina','Saten','Chifon'),
    IN  _tipo_pantalon ENUM('Jean','Jogger','Chino','Cargo','Buzo','Leggins','Palazzo','Otro'),
    IN  _largo_pierna DECIMAL(6,2),
    IN  _cintura      DECIMAL(6,2),
    IN  _elasticidad  TINYINT,
    IN  _activo       TINYINT
)
BEGIN
    UPDATE Prenda
       SET nombre        = _nombre,
           precioUnidad  = _precioUnidad,
           precioMayor   = _precioMayor,
           precioDocena  = _precioDocena,
           alertaMinStock= _alertaMinStock,
           color         = _color,
           material      = _material,
           activo        = _activo
     WHERE idPrenda = _id_prenda;

    UPDATE Pantalon
       SET tipo_pantalon = _tipo_pantalon,
           largo_pierna  = _largo_pierna,
           cintura       = _cintura,
           elasticidad   = _elasticidad
     WHERE idPrenda = _id_prenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificar_polo
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `modificar_polo`(
    IN  _id_prenda INT,
    IN  _nombre VARCHAR(100),
    IN  _precioUnidad DECIMAL(10,2),
    IN  _precioMayor  DECIMAL(10,2),
    IN  _precioDocena DECIMAL(10,2),
    IN  _alertaMinStock INT,
    IN  _color VARCHAR(30),
    IN  _material ENUM('Algodon','Poliester','Mezcla_algodon_poliester','Lino','Viscosa_rayon',
                       'Lana','Acrilico','Nylon','Elastano_lycra','Denim','Drill','Gabardina',
                       'Polar','Franela','Cuero','Cuerina','Saten','Chifon'),
    IN  _tipo_manga  ENUM('MangaCorta','MangaLarga','SinManga','Globo','Campana','TresCuartos'),
    IN  _estampado   VARCHAR(80),
    IN  _tipo_cuello ENUM('Redondo','V','Camisero','Alto','Halter','OffShoulder','Otro'),
    IN  _activo TINYINT
)
BEGIN
    UPDATE Prenda
       SET nombre = _nombre,
           precioUnidad = _precioUnidad,
           precioMayor  = _precioMayor,
           precioDocena = _precioDocena,
           alertaMinStock = _alertaMinStock,
           color = _color,
           material = _material,
           activo = _activo
     WHERE idPrenda = _id_prenda;

    UPDATE Polo
       SET tipo_manga  = _tipo_manga,
           estampado   = _estampado,
           tipo_cuello = _tipo_cuello
     WHERE idPrenda = _id_prenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificar_promocioncombo
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `modificar_promocioncombo`(in id int, in nomb VARCHAR(75),in cantReque int , in cantGrat int,in indV int)
BEGIN
		update Promocion 
        set nombre=nomb, idVigencia=indV 
        where idPromocion=id;
        
		update PromocionCombo 
        set cantidadRequerida=cantReque, cantidadGratis=cantGrat 
        where idPromocion=id;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificar_promocionconjunto
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `modificar_promocionconjunto`(in id int, in nomb VARCHAR(75),in promocion float,in indV int)
BEGIN
		update Promocion 
        set nombre=nomb, idVigencia=indV 
        where idPromocion=id;
        
		update PromocionConjunto 
        set porcentajePromocion=promocion 
        where idPromocion=id;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificar_proveedor
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `modificar_proveedor`(  IN _idProveedor INT,     
IN _RUC BIGINT,     IN _nombre VARCHAR(70),   
  IN _telefono INT,     IN _direccion VARCHAR(150), 
  IN _activo TINYINT)
BEGIN  
  
  UPDATE Proveedor SET RUC=_RUC,
  nombre=_nombre,telefono=_telefono,direccion=_direccion,activo=_activo
  WHERE idProveedor=_idProveedor;
  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure modificar_vestido
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `modificar_vestido`(
    IN  _id_prenda INT,
    IN  _nombre VARCHAR(100),
    IN  _precioUnidad DECIMAL(10,2),
    IN  _precioMayor  DECIMAL(10,2),
    IN  _precioDocena DECIMAL(10,2),
    IN  _alertaMinStock INT,
    IN  _color VARCHAR(30),
    IN  _material ENUM('Algodon','Poliester','Mezcla_algodon_poliester','Lino','Viscosa_rayon',
                       'Lana','Acrilico','Nylon','Elastano_lycra','Denim','Drill','Gabardina',
                       'Polar','Franela','Cuero','Cuerina','Saten','Chifon'),
    IN  _tipo_vestido ENUM('Coctel','Fiesta','Gala','Playa','Ejecutivo','Maxi','Mini','Casual'),
    IN  _tipo_manga   ENUM('MangaCorta','MangaLarga','SinManga','Globo','Campana','TresCuartos'),
    IN  _largo        INT,
    IN  _activo       TINYINT
)
BEGIN
    UPDATE Prenda
       SET nombre        = _nombre,
           precioUnidad  = _precioUnidad,
           precioMayor   = _precioMayor,
           precioDocena  = _precioDocena,
           alertaMinStock= _alertaMinStock,
           color         = _color,
           material      = _material,
           activo        = _activo
     WHERE idPrenda = _id_prenda;

    UPDATE Vestido
       SET tipo_vestido = _tipo_vestido,
           largo        = _largo,
           tipo_manga   = _tipo_manga
     WHERE idPrenda = _id_prenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure mostrar_almacenes
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `mostrar_almacenes`()
BEGIN
	SELECT *FROM Almacen;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure mostrar_almacenes_activos
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `mostrar_almacenes_activos`()
BEGIN
	SELECT *FROM Almacen
    WHERE activo=1;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure mostrar_blusas
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `mostrar_blusas`()
BEGIN
  SELECT *
    FROM Prenda p
    JOIN Blusa  b ON b.idPrenda = p.idPrenda;
    -- WHERE p.activo = 1;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure mostrar_casacas
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `mostrar_casacas`(
)
BEGIN
    SELECT  p.idPrenda, p.nombre, p.stockPrenda, p.precioUnidad, p.precioMayor, p.precioDocena,
            p.alertaMinStock, p.color, p.material,
            c.tipo_casaca, c.con_capucha
      FROM  Prenda p
      JOIN  Casaca c ON c.idPrenda = p.idPrenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure mostrar_descuentoporcentaje
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `mostrar_descuentoporcentaje`()
Begin

select dp.idDescuento, d.nombre as nombre,dp.porcentaje as porcentaje,d.idVigencia as idVigencia,d.esAutomatico as esAutomatico, d.activo as activo
 from DescuentoPorcentaje dp, Descuento d where d.idDescuento=dp.idDescuento;
End$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure mostrar_faldas
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `mostrar_faldas`()
BEGIN
  SELECT  *
    FROM  Prenda p
    JOIN  Falda  f ON f.idPrenda = p.idPrenda;
    -- WHERE p.activo = 1;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure mostrar_gorros
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `mostrar_gorros`()
BEGIN
  SELECT *
    FROM Prenda p
    JOIN Gorro  g ON g.idPrenda = p.idPrenda;
    -- WHERE p.activo = 1;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure mostrar_lotes
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `mostrar_lotes`()
BEGIN
	SELECT idLote, Almacen_idAlmacen, MovimientoAlmacen_idMovAlmacen,
    MovimientoAlmacen_Almacen_idAlmacen, activo FROM Lote;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure mostrar_lotes_activos
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `mostrar_lotes_activos`()
BEGIN 
	SELECT idLote, Almacen_idAlmacen, MovimientoAlmacen_idMovAlmacen,
    MovimientoAlmacen_Almacen_idAlmacen, activo FROM Lote
    WHERE activo=1;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure mostrar_mov_almacenes
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `mostrar_mov_almacenes`()
BEGIN
	SELECT idMovAlmacen, Almacen_idAlmacen, fecha, lugarDestino,
    lugarOrigen, tipo, activo FROM MovimientoAlmacen;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure mostrar_mov_almacenes_activos
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `mostrar_mov_almacenes_activos`()
BEGIN
	SELECT idMovAlmacen, Almacen_idAlmacen, fecha, lugarDestino,
    lugarOrigen, tipo, activo FROM MovimientoAlmacen
    WHERE activo=1;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure mostrar_pantalones
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `mostrar_pantalones`()
BEGIN
  SELECT *
    FROM Prenda   p
    JOIN Pantalon t ON t.idPrenda = p.idPrenda;
    -- WHERE p.activo = 1;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure mostrar_polos
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `mostrar_polos`()
BEGIN
	SELECT * FROM Prenda INNER JOIN Polo ON Prenda.idPrenda = Polo.idPrenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure mostrar_vestidos
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `mostrar_vestidos`()
BEGIN
  SELECT *
    FROM Prenda  p
    JOIN Vestido v ON v.idPrenda = p.idPrenda;
    -- WHERE p.activo = 1;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure obtenerId_cliente
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `obtenerId_cliente`( IN _idCliente INT)
BEGIN
  
	SELECT c.idCliente,p.nombre,
    p.primerApellido,p.segundoApellido,
    p.dni,p.telefono,p.genero,
    t.tipoCliente,t.abreviatura,t.descripcion
    FROM Cliente c INNER JOIN 
	Persona p ON c.idCliente=p.idPersona
	INNER JOIN TipoDeCliente t ON c.tipoCliente = t.tipoCliente 
    where c.idCliente=_idCliente;
    
  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure obtenerId_proveedor
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `obtenerId_proveedor`( IN _idProveedor INT)
BEGIN
  Select idProveedor,RUC,nombre,telefono,direccion,activo
  From Proveedor WHERE idProveedor=_idProveedor;
  END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure obtener_almacen_X_id
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `obtener_almacen_X_id`(
	IN _idAlmacen int
)
BEGIN
	SELECT idAlmacen, nombre, ubicacion, stock, Tienda_idTienda, activo
    FROM Almacen
    WHERE idAlmacen=_idAlmacen;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure obtener_blusa_X_id
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `obtener_blusa_X_id`(
    IN _id_prenda INT
)
BEGIN
  SELECT *
    FROM Prenda p
    JOIN Blusa  b ON b.idPrenda = p.idPrenda
   WHERE p.idPrenda = _id_prenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure obtener_descuentomonto_X_id
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `obtener_descuentomonto_X_id`(in id int)
BEGIN
	select d.idDescuento as idDescuento, d.nombre as nombre, dp.montoEditable as montoEditable,dp.montoMaximo as montoMaximo,
    d.activo as activo,
    d.esAutomatico as esAutomatico, d.idVigencia as idVigencia from DescuentoMonto dp, Descuento d 
    where d.idDescuento=id and dp.idDescuento=id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure obtener_descuentoporcentaje_X_id
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `obtener_descuentoporcentaje_X_id`(in id int)
BEGIN
	select d.idDescuento as idDescuento, d.nombre as nombre, dp.porcentaje as porcentaje,d.activo as activo,
    d.esAutomatico as esAutomatico, d.idVigencia as idVigencia from DescuentoPorcentaje dp, Descuento d 
    where d.idDescuento=id and dp.idDescuento=id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure obtener_falda_X_id
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `obtener_falda_X_id`(
    IN _id_prenda INT
)
BEGIN
    SELECT  p.idPrenda, p.nombre, p.stockPrenda, p.precioUnidad, p.precioMayor, p.precioDocena,
            p.alertaMinStock, p.color, p.material,
            c.tipo_falda, c.largo, c.con_forro, c.con_volantes
      FROM  Prenda p
      JOIN  Falda c ON c.idPrenda = p.idPrenda
     WHERE  p.idPrenda = _id_prenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure obtener_gorro_X_id
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `obtener_gorro_X_id`(
    IN _id_prenda INT
)
BEGIN
  SELECT *
    FROM Prenda p
    JOIN Gorro  g ON g.idPrenda = p.idPrenda
   WHERE p.idPrenda = _id_prenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure obtener_lote_X_id
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `obtener_lote_X_id`(
	_idLote int
)
BEGIN
	SELECT idLote, Almacen_idAlmacen, MovimientoAlmacen_idMovAlmacen,
    MovimientoAlmacen_Almacen_idAlmacen, activo FROM Lote
    WHERE _idLote=idLote;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure obtener_mov_X_id
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `obtener_mov_X_id`(
	_idMovAlmacen int
)
BEGIN
	SELECT idMovAlmacen, Almacen_idAlmacen, fecha,
    lugarDestino, lugarOrigen, tipo, activo
    FROM MovimientoAlmacen
    WHERE idMovAlmacen=_idMovAlmacen;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure obtener_pantalon_X_id
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `obtener_pantalon_X_id`(
    IN _id_prenda INT
)
BEGIN
  SELECT *
    FROM Prenda   p
    JOIN Pantalon t ON t.idPrenda = p.idPrenda
   WHERE p.idPrenda = _id_prenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure obtener_polo_X_id
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `obtener_polo_X_id`(
    IN _id_prenda INT
)
BEGIN
    SELECT  p.idPrenda, p.nombre, p.stockPrenda, p.precioUnidad, p.precioMayor, p.precioDocena,
            p.alertaMinStock, p.color, p.material,
            po.tipo_manga, po.estampado, po.tipo_cuello
      FROM  Prenda p
      JOIN  Polo   po ON po.idPrenda = p.idPrenda
     WHERE  p.idPrenda = _id_prenda;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure obtener_vestido_X_id
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`admin`@`%` PROCEDURE `obtener_vestido_X_id`(
    IN _id_prenda INT
)
BEGIN
  SELECT *
    FROM Prenda  p
    JOIN Vestido v ON v.idPrenda = p.idPrenda
   WHERE p.idPrenda = _id_prenda;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
