-- MySQL Script generated by MySQL Workbench
-- Tue Sep 16 02:31:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tienda` (
  `idTienda` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NULL DEFAULT NULL,
  `ubicacion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTienda`),
  UNIQUE INDEX `idTienda_UNIQUE` (`idTienda` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Almacen` (
  `idAlmacen` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NULL DEFAULT NULL,
  `ubicacion` VARCHAR(70) NULL DEFAULT NULL,
  `stock` INT NOT NULL,
  `Tienda_idTienda` INT NOT NULL,
  `Activo` TINYINT NOT NULL,
  PRIMARY KEY (`idAlmacen`),
  INDEX `fk_Almacen_Tienda1_idx` (`Tienda_idTienda` ASC) VISIBLE,
  CONSTRAINT `fk_Almacen_Tienda1`
    FOREIGN KEY (`Tienda_idTienda`)
    REFERENCES `mydb`.`Tienda` (`idTienda`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Catalogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Catalogo` (
  `idCatalogo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NULL DEFAULT NULL,
  `Tienda_idTienda` INT NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`idCatalogo`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_Catalogo_Tienda1_idx` (`Tienda_idTienda` ASC) VISIBLE,
  CONSTRAINT `fk_Catalogo_Tienda1`
    FOREIGN KEY (`Tienda_idTienda`)
    REFERENCES `mydb`.`Tienda` (`idTienda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`LineaDeRopa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LineaDeRopa` (
  `idLinea` INT NOT NULL AUTO_INCREMENT,
  `nombreLinea` VARCHAR(70) NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `Catalogo_idCatalogo` INT NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`idLinea`),
  INDEX `fk_LineaDeRopa_Catalogo1_idx` (`Catalogo_idCatalogo` ASC) VISIBLE,
  CONSTRAINT `fk_LineaDeRopa_Catalogo1`
    FOREIGN KEY (`Catalogo_idCatalogo`)
    REFERENCES `mydb`.`Catalogo` (`idCatalogo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`MovimientoAlmacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MovimientoAlmacen` (
  `idMovAlmacen` INT NOT NULL AUTO_INCREMENT,
  `Almacen_idAlmacen` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `lugarDestino` VARCHAR(100) NOT NULL,
  `lugarOrigen` VARCHAR(100) NOT NULL,
  `tipo` ENUM('Entrada', 'Salida', 'Mov_Interno') NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`idMovAlmacen`, `Almacen_idAlmacen`),
  INDEX `fk_MovimientoAlmacen_Almacen1_idx` (`Almacen_idAlmacen` ASC) VISIBLE,
  CONSTRAINT `fk_MovimientoAlmacen_Almacen1`
    FOREIGN KEY (`Almacen_idAlmacen`)
    REFERENCES `mydb`.`Almacen` (`idAlmacen`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lote` (
  `idLote` INT NOT NULL AUTO_INCREMENT,
  `Almacen_idAlmacen` INT NOT NULL,
  `MovimientoAlmacen_idMovAlmacen` INT NOT NULL,
  `MovimientoAlmacen_Almacen_idAlmacen` INT NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`idLote`, `MovimientoAlmacen_idMovAlmacen`, `MovimientoAlmacen_Almacen_idAlmacen`),
  INDEX `fk_Lote_Almacen1_idx` (`Almacen_idAlmacen` ASC) VISIBLE,
  INDEX `fk_Lote_MovimientoAlmacen1_idx` (`MovimientoAlmacen_idMovAlmacen` ASC, `MovimientoAlmacen_Almacen_idAlmacen` ASC) VISIBLE,
  CONSTRAINT `fk_Lote_Almacen1`
    FOREIGN KEY (`Almacen_idAlmacen`)
    REFERENCES `mydb`.`Almacen` (`idAlmacen`),
  CONSTRAINT `fk_Lote_MovimientoAlmacen1`
    FOREIGN KEY (`MovimientoAlmacen_idMovAlmacen` , `MovimientoAlmacen_Almacen_idAlmacen`)
    REFERENCES `mydb`.`MovimientoAlmacen` (`idMovAlmacen` , `Almacen_idAlmacen`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Prenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prenda` (
  `idPrenda` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NOT NULL,
  `talla` VARCHAR(30) NOT NULL,
  `color` VARCHAR(30) NOT NULL,
  `stock` INT NOT NULL,
  `alertaMinima` INT NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`idPrenda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`PrecioBase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PrecioBase` (
  `Prenda_idPrenda` INT NOT NULL,
  `precioUnidad` DECIMAL(10,2) NOT NULL,
  `precioCuarto` DECIMAL(10,2) NOT NULL,
  `precioDocena` DECIMAL(10,2) NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`Prenda_idPrenda`),
  CONSTRAINT `fk_PrecioBase_Prenda1`
    FOREIGN KEY (`Prenda_idPrenda`)
    REFERENCES `mydb`.`Prenda` (`idPrenda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`PrendaLote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PrendaLote` (
  `Prenda_idPrenda` INT NOT NULL,
  `Lote_idLote` INT NOT NULL,
  `Lote_MovimientoAlmacen_idMovAlmacen` INT NOT NULL,
  `Lote_MovimientoAlmacen_Almacen_idAlmacen` INT NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`Prenda_idPrenda`, `Lote_idLote`, `Lote_MovimientoAlmacen_idMovAlmacen`, `Lote_MovimientoAlmacen_Almacen_idAlmacen`),
  INDEX `fk_Prenda_has_Lote_Lote1_idx` (`Lote_idLote` ASC, `Lote_MovimientoAlmacen_idMovAlmacen` ASC, `Lote_MovimientoAlmacen_Almacen_idAlmacen` ASC) VISIBLE,
  INDEX `fk_Prenda_has_Lote_Prenda1_idx` (`Prenda_idPrenda` ASC) VISIBLE,
  CONSTRAINT `fk_Prenda_has_Lote_Lote1`
    FOREIGN KEY (`Lote_idLote` , `Lote_MovimientoAlmacen_idMovAlmacen` , `Lote_MovimientoAlmacen_Almacen_idAlmacen`)
    REFERENCES `mydb`.`Lote` (`idLote` , `MovimientoAlmacen_idMovAlmacen` , `MovimientoAlmacen_Almacen_idAlmacen`),
  CONSTRAINT `fk_Prenda_has_Lote_Prenda1`
    FOREIGN KEY (`Prenda_idPrenda`)
    REFERENCES `mydb`.`Prenda` (`idPrenda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`Vigencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vigencia` (
  `idVigencia` INT NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `LineaDeRopa_idLinea` INT NOT NULL,
  `activo` TINYINT NOT NULL,
  PRIMARY KEY (`idVigencia`),
  INDEX `fk_Vigencia_LineaDeRopa1_idx` (`LineaDeRopa_idLinea` ASC) VISIBLE,
  CONSTRAINT `fk_Vigencia_LineaDeRopa1`
    FOREIGN KEY (`LineaDeRopa_idLinea`)
    REFERENCES `mydb`.`LineaDeRopa` (`idLinea`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
